name: Build WUPS Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install WUPS
        run: |
          dkp-pacman -Syu --noconfirm
          dkp-pacman -S --noconfirm wiiu-dev wut-tools wups-dev

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CrashCombo
          path: "*.wps"
